### ISSUE TITLE
Suggestion for using plugins that is maintained

### ISSUE THREAD

**Issue by ExHix** [noccu/umamusu-translate#16]
The original translate plugin repo has been archived and no longer been maintained, so I suggest using [this](https://github.com/MinamiChiwa/Trainers-Legend-G) plugin, which is forked from the original one and I am using now.  
It has fixed several bugs and embedded new functions, such as replacing the texture/picture in-game (which can be used to translate the text that is hardcoded into the picture), much better format to store translation text and auto line breaking.  
This plugin is still in-supported, and although this repo is for Chinese translation, the `version.dll` is universal. I will contact the maintainer of this repo if you guys have any technical questions about it. I can also provide some basic information about it.

**Comment by noccu** [comment]
I wasn't aware there was a maintained fork, sounds very interesting.
Thanks for bringing it to my attention, I'll have a look at it soon.

**Comment by noccu** [comment]
So I took a look and it does look nice in some respects, notably extracting/replacing more text hashes which the original localify seems to have stopped processing, and text -> text static translations.
However, automatic linebreaks have stopped working. Text will run off the screen and the linebreak-mode changing doesn't seem to do anything at all. In fact it seems like unlimited overflow is allowed everywhere. Can you provide or ask any insights?
Free window resizing also no longer works for me. (`"unlockSize": true`)

As an aside, while likely not related to the plugin itself, does anyone know why `version.dll` doesn't load for some players?
This was an issue with localify as well. For me, for example, the game seems to skip local directory checking altogether for version.dll and loads it straight from `system32`. The workaround used is to rename the file to `uxtheme.dll`, but I imagine this may cause other issues as functions are not correctly proxied. That is if they are used at all, so far I have not found (verified) problems with it, and while I doubt it has anything to do with the linebreak issue, there's always a chance. I have not looked deeply into the localify code.

**Comment by ExHix** [comment]
Welp I can't help you to solve the technical problem for I don't understand its code either, but that repo now has opened a discord server,  and I think you can ask the developer here.
