### ISSUE TITLE
Incomplete Words / Translation Suggestions

### ISSUE THREAD

**Issue by verrmilion** [noccu/umamusu-translate#2]
This may already be known, but the character page for each Uma has Wisdom listed as `Wis`. I'm not sure if this is intentional or not, but I see that `Stamina` is written completely, so I figured why not.

I believe that the translation is in [static_en.json](https://github.com/noccu/umamusu-translate/blob/master/src/static/data/static_en.json), since that's where I found it.

Another thing is that, when applying the patches for **Dialogue** and **UI**, the Uma page has a lot of words which are incomplete, for example, `Grass` is written as `Gr`, `Betweener` as `Bet`, etc., as it can be seen in the image below. This is issue is fixed by the time the **Skills** patch is applied, but the `Wis` problem remains.

![image](https://user-images.githubusercontent.com/96276112/155727494-96e1d035-92bd-48d6-a191-41713e73c482.png)

Finally, I would like to suggest changing `Grass` to `Turf` in true horse racing spirit, since, from what I understand `芝` means turf.

**Comment by noccu** [comment]
Grass and Wis are leftover artifacts from early on, I'll fix those in the next update.

For the rest unfortunately the game really limits the space available for text and sometimes treats English text with different spacing rules on top of that so there isn't much that can be done.
Sometimes changing font size or adding a manual wordbreak can help, and localify itself attempts to fix a few spacing/linebreak issues but can't deal with them all, and I'm too busy to have a look at it with my limited experience right now.
Let me know if you find any other instances and I can take a look case by case, or — as you've found out — editing the text is rather easy so anyone can have a play themselves.
