### ISSUE TITLE
connection error 102

### ISSUE THREAD

**Issue by arthuritalo** [noccu/umamusu-translate#26]
![image](https://user-images.githubusercontent.com/11094457/186891347-3d2afbe2-b5cc-4586-beb3-1966de88992d.png)

I'm having this problem when i do this steps:

![image](https://user-images.githubusercontent.com/11094457/186891555-bc5d511a-17f5-41bd-89b5-45df66d60970.png)

![image](https://user-images.githubusercontent.com/11094457/186891626-9708c5e1-0e3f-41c4-bb8f-252df52c5070.png)

![image](https://user-images.githubusercontent.com/11094457/186891668-2d591621-ef74-40aa-b1f4-b597655cd2d8.png)

![image](https://user-images.githubusercontent.com/11094457/186891711-e2b5fd90-7a64-4de9-a867-0887245c57e3.png)

after this my game pop-up the error 102 and i return to the tittle screen

**Comment by noccu** [comment]
Fixed in e23aa6d07886f11df9b31e9863428e4479a8a150
