### ISSUE TITLE
Requesting removal of my submissions

### ISSUE THREAD

**Issue by robflop** [noccu/umamusu-translate#47]
Hello, I'm writing this issue to request removal of all content I've submissed to this repository. A listing can be found at the end of this text.

The reason for this is the planned monetization of the project that can be seen in commit 6ae7e2f (which adds code for "supporter-exclusive" content that one must pay to access) as well as the paid-only announcement regarding the same topic on the website ko-fi.com located at this url:  https://ko-fi.com/post/UmaTL-Supporters-Edition-H2H8KRDEB. I cannot verify the actual content of the announcement as it is paid-only, but the title seems to indicate it being related.

The work I've contributed was only to be used within the context of a fully free to access fan project. Since this content originally belongs to Cygames, no person involved in the project has rights to monetizing it, which is why I believe that I cannot leave the content I've submitted as a part of this project.

As the project did not specify any license terms at the point the below listed contributions took place, and still does not at the point of writing this issue, the rights to all content submitted by individuals fully remains with the contributors according to GitHub's own documentation, as specified in https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository. Therefore, I'm making use of my right to request removal of my contributions.

The list of content I request removal of is as follows:
- The preview text for the "Illuminate the Heart" story event: b7cde6b
- The full translation for the "Illuminate the Heart" story event: 375ac05 (Pull Request #39)
- The translations of the Vodka SSR support card training events: 5f304b3 (Pull Request #8)
- The translations of the Vodka SR support card training events: b766230 (Pull Request #7)
- The translations of the Vodka R support card training events: c038cef (Pull Request #6)
- The translations of Vodka's character story: 4031015 (Pull Request #1)
- Any other mention of my (user-)name in the repository's files not listed in the above (for example but not only in credit lists as well as translation progress overviews, for both completed and pending work)

Thank you.

**Comment by robflop** [comment]
I am still looking for this request to be fulfilled.

**Comment by robflop** [comment]
@CryDuringItAll kindly contacted me personally and offered to create a pull request which would resolve this issue. I've accepted their offer, the result you can see in #49 - it replaces all the work I've listed in my issue, as well as attributions to me, with translation via Sugoi MTL that is built into this project. I'd be happy if you could merge it to resolve this issue.

**Comment by noccu** [comment]
As you have given your approval of it, PR #49 will be merged to implement your request.

This follows the project's policy, clarified below:
Underpinning this project lies a belief that it does not inflict undue harm upon the game or its rightsholders, and an intent to provide a positive impact by engaging players with what it has to offer, drawing in new players, and generally enhancing accessibility to those who do not speak the language.
This is accompanied by awareness of applicable legal frameworks, the project's place within them, and the commitment to comply with them when required.
Naturally, the legal rights of the community's translators and other contributors are equally recognized. To determine these rights, geographic location of the contributor in question forms the key factor. 
Conversely, should new information become available or relevant circumstances otherwise change in such a way that previous decisions or claims become invalid or unknown, this may lead to re-evaluations and restoration of content in accordance with this policy.

Finally, I want to clear up a possible misunderstanding to readers by noting that all community contributions remain accessible in the community edition and exclusive content is solely the work of the project team. (this was also communicated in DM)

**Comment by robflop** [comment]
Thank you. A follow-up question and a note regarding your stated policy:

I am assuming you have also removed my content (as listed previously) from the supporters only version, is that correct? The issue talks about the project at large, not only the free edition (what you call the community version), but also about the paid edition (what you call the supporters edition). I cannot verify the latter (since I have no access, and will not take the steps to gain it due to the nature of this issue), so I would like your word for it.

Regarding the stated policy:

> Conversely, should new information become available or relevant circumstances otherwise change in such a way that previous decisions or claims become invalid or unknown, this may lead to re-evaluations and restoration of content in accordance with this policy.

As I have stated in the original message of this issue (a quote can be found below), I do not waive any of the rights given to me for my contributions to this repository in GitHub's terms of service. Should it come to a case in which you wish to restore any of the content I have previously submitted to this repository, I especially retain the rights to deciding whether I allow or do not allow you to use my work in this restoration. Please contact me **before** you carry out any steps towards content restoration via a message in this issue and wait for my response.

The aforementioned quote:
> As the project did not specify any license terms at the point the below listed contributions took place, and still does not at the point of writing this issue, the rights to all content submitted by individuals fully remains with the contributors according to GitHub's own documentation, as specified in https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository. Therefore, I'm making use of my right to request removal of my contributions.

**Comment by noccu** [comment]
> I am assuming you have also removed my content (as listed previously) from the supporters only version, is that correct? The issue talks about the project at large, not only the free edition (what you call the community version), but also about the paid edition (what you call the supporters edition). I cannot verify the latter (since I have no access, and will not take the steps to gain it due to the nature of this issue), so I would like your word for it.

Yes, the supporters edition keeps up to date with community updates.

**Comment by robflop** [comment]
Thank you for the confirmation.
