### ISSUE TITLE
Error when run Install.bat

### ISSUE THREAD

**Issue by Cynga98** [noccu/umamusu-translate#51]
Hello. I don't know what happened, and it's said I need to screenshot all of it. 

Thank you so much

![error](https://github.com/noccu/umamusu-translate/assets/137014124/c17ea57c-4403-4eb6-965d-b9a2e416e1e3)

**Comment by noccu** [comment]
The "pip" module python uses to install dependencies is missing in your install. This is rather rare as it comes with python and is heavily relied on.

If you can open a cmd prompt in the patch folder this should take care of it:
```bat
.venv\Scripts\activate.bat
py -m ensurepip --upgrade
```
See here for more info: https://pip.pypa.io/en/stable/installation/

**Comment by Cynga98** [comment]
so i just need to open cmd and copy paste that? sorry if i ask too much because im blind with this kind stuff

**Comment by noccu** [comment]
Oops, forgot about this, sorry, but yes. I'll assume you have solved it by now.
